[
  [
    [{: name => "Cards in column: Completed 28th - 4th Dec",
  : list_id => "5837a1118ca8a7303d282b58",
  : cards => [{: id => "5842bba70b373fe67183f307",
  : name => "Check if suggestions go outside screen",
  : description => "",
  : url => "https://trello.com/c/B5hk43No/117-check-if-suggestions-go-outside-screen",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "5842de6cbf1086eec1ad8655",
  : name => "Hightlight today's date in datepicker",
  : description => "",
  : url => "https://trello.com/c/fYexZ1cq/118-hightlight-today-s-date-in-datepicker",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "5840e63c2af8cd677125eac1",
  : name => "Add placeholder text of current date to the date field",
  : description => "Helpful placeholder text gives context to the user.\n\nWhy show the day e.g. Friday:\nHelps the user know they chose the date correctly. Meetings are regularly scheduled by the day and the date.",
  : url => "https://trello.com/c/7hLFJOvP/110-add-placeholder-text-of-current-date-to-the-date-field",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583fcc64a9e3abe3da1b680f",
  : name => "Add ability to select time via drop downs",
  : description => "",
  : url => "https://trello.com/c/u8RkFHOr/104-add-ability-to-select-time-via-drop-downs",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "5840e103b50f8e882be4127b",
  : name => "Make arrow for attachment menu visible",
  : description => "In Create a Meeting, the uploaded attachments menu is not visible to people. \nTask: Make it visible.",
  : url => "https://trello.com/c/qQ12OJ4C/109-make-arrow-for-attachment-menu-visible",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "58423a0c231084c41dbbf449",
  : name => "Add ability to add places not only from Google places",
  : description => "Copy value from search place input to place-name input if no place was selected from Google suggestions",
  : url => "https://trello.com/c/4sjOUe6g/116-add-ability-to-add-places-not-only-from-google-places",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "5840e7e1cc26a9f644168c22",
  : name => "Edit text in Create a New Meeting",
  : description => "See attachment for copy updates",
  : url => "https://trello.com/c/iQaZiq0v/111-edit-text-in-create-a-new-meeting",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583ef8443a680c10edc46e11",
  : name => "Update details on Minutes",
  : description => "Refer to attachment and checklist",
  : url => "https://trello.com/c/wNZG35q4/96-update-details-on-minutes",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "581db4ae3a2f8978e12413fd",
  : name => "Delete Meeting",
  : description => "",
  : url => "https://trello.com/c/kDCjkaqh/42-delete-meeting",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "583fd0c9217e397e3d24714d",
  : name => "Basic Edit Form validation",
  : description => "",
  : url => "https://trello.com/c/7YyDbwia/107-basic-edit-form-validation",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583fdb344043c3319c5157d9",
  : name => "Add .ics + .atom",
  : description => "",
  : url => "https://trello.com/c/nkE1EYYJ/108-add-ics-atom",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "581db4f3a208f1ada48f14bf",
  : name => "[meetings] Print detail",
  : description => "",
  : url => "https://trello.com/c/DvjbPeaU/44-meetings-print-detail",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "583e7b9c6183178af135ba2f",
  : name => "Prevent Agenda item from expanding if it's a model",
  : description => "",
  : url => "https://trello.com/c/o19SV6uG/81-prevent-agenda-item-from-expanding-if-it-s-a-model",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583f9f0b4519989d4eb56d5b",
  : name => "Medium Editor doesn't work in Meetings Details. Works everywhere else",
  : description => "",
  : url => "https://trello.com/c/XcvV1waG/102-medium-editor-doesn-t-work-in-meetings-details-works-everywhere-else",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583ea6bcb29244a2cbb74b04",
  : name => "Remove scary text",
  : description => "**\"It cannot be undone!\"** is extremely frightening. We need to be informative but not traumatising.\n\nNote: **Meetings with minutes cannot be deleted.** This is because committees must keep their records for 7 years.",
  : url => "https://trello.com/c/sgrBVe4N/83-remove-scary-text",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583ede3c8f6ece8d6b62f114",
  : name => "Update Invite Attendees Modal",
  : description => "",
  : url => "https://trello.com/c/kS883Q6q/93-update-invite-attendees-modal",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}, {: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "583f55b45b0167603cb54504",
  : name => "If no suggestion return completely empty respond",
  : description => "",
  : url => "https://trello.com/c/uwL6aGWT/101-if-no-suggestion-return-completely-empty-respond",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "583ef0e3b30653466cb3691f",
  : name => "Add the time of the meetings in the Meeting Index list",
  : description => "",
  : url => "https://trello.com/c/gAlgMdgi/94-add-the-time-of-the-meetings-in-the-meeting-index-list",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "583ef44d03bd0b862b248611",
  : name => "Consider removing the minutes meatballs menu",
  : description => "If we have valid reasons for this menu and decide to keep it then:\n\nChange **Remove Minute** to **Remove Agenda Item**.\n\nThe minutes are the notes to the agenda item.",
  : url => "https://trello.com/c/WDulRf8k/95-consider-removing-the-minutes-meatballs-menu",
  : due => nil,
: closed => false,
: members => []
}, {: id => "583ed3fa344c64a3cbf949d8",
  : name => "Remove Custom Message Textbox",
  : description => "Remove Custom Message Textboxes from inviting modals and use existing Meetings email",
  : url => "https://trello.com/c/wJrvBUZ5/90-remove-custom-message-textbox",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583ef929abdeea2bc949242f",
  : name => "Hide Collaborators feature",
  : description => "Hiding because we need to edit the text on that modal.\nAnd answer questions like:\nHow does it give people access differently to being an admin? What kind of email does the collaborator receive to let them know they are a collaborator?",
  : url => "https://trello.com/c/fTbXgfZ2/97-hide-collaborators-feature",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "583ed5b0321279ef56b22360",
  : name => "Update Layout in App",
  : description => "",
  : url => "https://trello.com/c/7jOIoWCm/91-update-layout-in-app",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583efb6b152aaa571ac72308",
  : name => "Fix up buttons at bottom of Create a Meeting and Minutes",
  : description => "If centre align looks harder to use then at the minimum these buttons need to be swapped so the negative action (cancel) is on the left and positive (Save) on the right.",
  : url => "https://trello.com/c/4iqBp4UJ/98-fix-up-buttons-at-bottom-of-create-a-meeting-and-minutes",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583eac16a6d0e951479e28fd",
  : name => "Remove unhandled tasks",
  : description => "We will be implementing tasks in a different way. This can be removed from phase 1.",
  : url => "https://trello.com/c/aK3v2NNf/84-remove-unhandled-tasks",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583eb8c2a93d96377f137db4",
  : name => "Switch order of Minute Taker and Chairperson fields",
  : description => "Chairperson runs the meeting so they are the first person to select\nthen\nMinute Taker",
  : url => "https://trello.com/c/THD8PyQd/87-switch-order-of-minute-taker-and-chairperson-fields",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "581db4ef0695fc417b8eec2a",
  : name => "[meetings] Make public?",
  : description => "When you select 'Make it public' it publishes a view to the public page. You can then 'Hide from public'. You could just update the label of the link to switch between: 'Make it Public' and 'Hide from Public'. \n\nI don't even know how many people use this – I don't think people even use it.",
  : url => "https://trello.com/c/yJPkBaWQ/43-meetings-make-public",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "5824b59a491470faace91feb",
  : name => "Visual editor doesn't work with HTML correct",
  : description => "",
  : url => "https://trello.com/c/6jqPzqrI/48-visual-editor-doesn-t-work-with-html-correct",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "582549d6ea990ea9d0e52878",
  : name => "Select Chair Person + Minute Taker should be from USERS not all members?",
  : description => "",
  : url => "https://trello.com/c/rw5HkcMh/51-select-chair-person-minute-taker-should-be-from-users-not-all-members",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "583d40c29fea7f262d89723b",
  : name => "Upload attachments in minutes edit",
  : description => "",
  : url => "https://trello.com/c/3xUI0rhK/79-upload-attachments-in-minutes-edit",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "581db29ef7e1d3c8c8e45d9c",
  : name => "Lock Meeting",
  : description => "",
  : url => "https://trello.com/c/RUFlH4kn/37-lock-meeting",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "5825e4579d3f4c94791eaaf7",
  : name => "Add New Place on the fly",
  : description => "",
  : url => "https://trello.com/c/fdnIsWD9/54-add-new-place-on-the-fly",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583bfb0543df8bd8f4815ac7",
  : name => "Columns different size",
  : description => "",
  : url => "https://trello.com/c/SnADpn7r/78-columns-different-size",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "583559f495ce20165875eefe",
  : name => "Split invitees to 3 columns",
  : description => "",
  : url => "https://trello.com/c/th56Cl8o/71-split-invitees-to-3-columns",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "583bec4e7a9f8f461a3cf175",
  : name => "New places interface (based on google suggestions)",
  : description => "",
  : url => "https://trello.com/c/XHYJcTwC/77-new-places-interface-based-on-google-suggestions",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}, {: id => "58351535ed7d7cb605928708",
  : name => "Using 'backend' id for attachement",
  : description => "",
  : url => "https://trello.com/c/F5Hieloq/68-using-backend-id-for-attachement",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "58368ebdccb6c7ccb0e114db",
  : name => "Sub-agenda items has empty parent_id",
  : description => "",
  : url => "https://trello.com/c/zbUOv7s9/74-sub-agenda-items-has-empty-parent-id",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "58368ef40e94c1b93cf3747f",
  : name => "Some js code still using  THQ.getUID()",
  : description => "",
  : url => "https://trello.com/c/upb9vExN/75-some-js-code-still-using-thq-getuid",
  : due => nil,
: closed => false,
: members => [{: id => "5779fb58b80dc23dc02b5cea",
  : username => "aleksgurianov",
  : full_name => "Aleks Gurianov",
  : url => "https://trello.com/aleksgurianov"
}]
}, {: id => "581db3e34b0f01e2cae5d581",
  : name => "Manage Collaborators",
  : description => "",
  : url => "https://trello.com/c/62SUKGPf/39-manage-collaborators",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}]
}, {: name => "Cards in column: Doing",
  : list_id => "57fb4eda5487203418166e05",
  : cards => [{: id => "583fc6db1a48b98f55f8f9b3",
  : name => "Tasks in minute taking",
  : description => "Tasks in taking minutes:\n\n1. Add ability to create or link existing tasks to meeting agenda item whlie taking minutes. See \"Add a task...\" attachment.\n\n2. Suggest tasks based on search results. Suggest tasks that match what is being typed. i.e. Task suggestion only appears if query is not empty and query matches existing tasks.",
  : url => "https://trello.com/c/Yvp2yqzv/103-tasks-in-minute-taking",
  : due => nil,
: closed => false,
: members => [{: id => "513f7fb0c498f96d20000aef",
  : username => "mpak",
  : full_name => "Renat",
  : url => "https://trello.com/mpak"
}]
}]
}, {: name => "Cards in column: Done",
  : list_id => "57fb4edcc0f08debf6b1775b",
  : cards => []
}]
]
]
